name: Cypress Tests
on: push
jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v2
 
     - name: Run Cypress Test
       uses: cypress-io/github-action@v4
       with:
         command: npm run test:registerTest
         #browser: chrome
         -name:Cypress Test Report
         - uses: actions/upload-artifact@v4
           with:
             name: Mochawesome HTML Report
             path: path/to/artifact/ # or path/to/artifact